name: smart_loading_app
description: "Een app voor het optimaliseren van het laden van vrachtcontainers."
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_cube: ^0.1.1  # 3D-weergave
  provider: ^6.0.5      # State management
  path_provider: ^2.0.15  # Bestandsbeheer
  excel: ^2.1.0         # Excel import/export
  pdf: ^3.8.4           # PDF export
  http: ^0.13.5         # API-requests
  shared_preferences: ^2.2.0  # Instellingen opslaan

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/models/container.glb  # 3D-model voor de container
