name: smart_loading_app
description: Een app met meertalige ondersteuning.
version: 1.4.0
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cube: ^0.1.2
  file_picker: ^6.1.1
  excel: ^2.0.4
  pdf: ^3.8.4
  printing: ^5.11.0
  http: ^0.13.5
  shared_preferences: ^2.2.1

flutter:
  uses-material-design: true
  assets:
    - lib/l10n/
