name: smart_loading_app
description: Een app voor containerberekening.
version: 1.0.0
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_cube: ^0.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/cube.obj
